version: "3"
services:
  ############ module container ############
  user-services:
    container_name: user-services
    build:
      context: .
      dockerfile: Dockerfile
    image: node:18.7
    ports:
      - "3000:3000"
   
  