import swaggerAutogen from "swagger-autogen";
const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/api",
  schemes: ["http", "https"],
};

const outputFile = "./swagger_output.json";

const endpointsFiles = ["./app/router/router.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  import("./server.js");
});
